<?
class Win10Ext{
	const ImageWithOneLine;
	const ImageWithTwoLines;
	const ImageWithThreeLines;
	const TextOneLine;
	const TextTwoLines;
	const TextThreeLines;
	
	const FirstLine;
	const SecondLine;
	const ThirdLine;
	
	public function __construct($appname){}
	public function SetWindowBlur( $hwnd ){}
	public function InitializeToast($msg_type){}
	public function SetImage($img_path){}
	public  function SetTextField($field_pos, $text){}
	public function ShowNotification(){}
	
}