<?

// возвращает версию Win
function osinfo_winver(){}

// возвращает версию DOS
function osinfo_dosver(){}

// возвращает true если программа запущена под NT
function osinfo_isnt(){}

// возвращает последнюю версию установленного .NET
function osinfo_dotnet(){}

// возвращает одну из настроек ќ—
function osinfo_locale($flag){}

// возвращает размер (в байтах) оперативной пам€ти компьютера (виртуальной или физической)
function osinfo_memory($flag){}

// возвращает серийный номер диска $disc
function osinfo_diskserial($disc){}

// возвращает true если программа запущена под админом
function osinfo_isadmin(){}

// возвращает размер диска в байтах
function osinfo_disktotal($disc){}

// возвращает количество свободного места на диске в байтах
function osinfo_diskfree($disc){}

// возвращает тип диска int
function osinfo_drivetype($disc){}

// возвращает сетевое им€ компьютера
function osinfo_computername(){}

// возвращает им€ пользовател€
function osinfo_username(){}

// возвращает код системного €зыка
function osinfo_syslang(){}

// вовзращает mac-адресс компьютера
function osinfo_macaddress(){}

