<?

function replaceSr($str){}
function replaceSl($str){}

// играет системный звук
function message_beep($flag){}

// возвращает псевдо-случайно целое число от 0 до X
function random($x){}

// копирует текст в буфер обмена
function clipboard_setText($text){}

// возвращает текст из буфера обмена
function clipboard_getText(){}

// копирует массив файлов в буфер
function clipboard_setFiles($files){}

// возвращает массив файлов из буфера
function clipboard_getFiles(){}

//Закрывает всю программу
function halt(){}

function pre2($mixed){}

function confirm($msg){}

function cntr_parent($control, $parent){}

function __message($msg){}

function __rtii_set($obj, $prop, $v){}

function __rtii_link($self, $prop_name){}

function __rtii_get($obj, $prop){}

function __rtii_exists($obj, $prop){}

function __rtii_class($obj){}

function __rtii_set_object($self, $prop, $obj){}

function __rtii_is_class($obj, $class){}

function control_repaint($obj){}

function control_doublebuffer($obj, bool $v){}

function convert_file_to_bmp($source, $bmp){}

function object_is_nil($obj){}

function bitmap_empty(TBitmap $bmp){}

function component_index($obj){}

function control_helpkeyword($obj, $htKeyword){}

function control_w($obj, $v){}

function control_h($obj, $v){}

function control_x($obj, $v){}

function control_y($obj, $v){}

function control_hint($obj, $text){}

function control_visible($obj, bool $v){}

function control_to_front($obj){}

function __SetVarEx_old($obj){}

function include_encode($file){}

function include_enc($file){}

function copyer_add($obj, $param){}

function copyer_insert($obj, $param){}

function control_to_back($obj){}

function component_copy($obj, $parent){}

function link_null($link){}

function tabcontrol_indexofxy($obj, $x, $y){}

function control_maxmin($obj, $v1, $v2){}

function control_invalidate($obj){}

function delay($ms){}

function fileexists($file){}

function show_hint($object, $text, $delay){}

function datetime_str($format){}

function str_datetime($format){}

function pagecontrol_activepage($obj, $page_self){}

function pagecontrol_pagecount($obj){}

function pagecontrol_pages($obj, $id){}

function getabsolutex($obj, $parent){}

function getabsolutey($obj, $parent){}

function control_focused($obj){}

function idle_enable($obj){}

function xxxx(){}

function cntr_owner5($obj){}

function include_get($param1, $param2){}

function scrollbox_vsshowing($obj){}

function scrollbox_hsshowing($obj){}

function scrollbox_sbsize($obj){}

function runcode($code){}

function component_name($obj){}

function control_text($prop, $text){}

function component_create($class, $owner){}

function findcomponent($name){}

function __copyright(){}

function string2stream($obj, $str){}

function include_enc2($file){}

function novisual_loadfile($obj, $bmp_file){}

function novisual_clear($obj){}

function tevent_text($prop, $str){}

function thread_include_enc2($thread, $file){}

function b64_encode($str, $param){}

function b64_decode($str, $param){}

function wtime_str($str){}

function str_wtime($str){}

function set_fatal_handle($handle){}

function set_event_old($obj, $event, $function){}

function s_gl($func_obj, $function){}

function gl($func_obj){}

function reg_component($owner, $name){}

function find_component($self, $name){}

function set_main_form($form){}

function get_application(){}

function component_count($self){}

function component_by_id($obj, $id){}

function control_focus($obj){}

function ______phpfunction1($param1){}

function control_count($self){}

function control_by_id($obj, $id){}

function get_event($obj, $event){}

function gui_componenttostring($str){}

function gui_stringtocomponent($self, $str){}

function gui_getscrollpos($obj, $bar_id){}

function  gui_setScrollPos($obj, $param2, $pos, $param4){}

function form_show_modal($form){}

function __tcursor($form){}

function font_prop($obj, $prop, $v){}

function form_close($form){}

function font_get($obj, $prop){}

function tabsheet_parent($obj, $v){}

function font_assign($obj1, $obj2){}

function form_modalresult($form, $v){}

function form_scrollby($form, $x, $y){}

function form_parent($form, $v){}

function screen_form_count(){}

function screen_form_by_id($id){}

function screen_form_active(){}

function cursor_pos_x(){}

function cursor_pos_y(){}

function application_terminate(){}

function application_minimize(){}

function application_processmessages(){}

function application_restore(){}

function application_messagebox($msg, $caption, $mode){}

function application_find_component($name){}

function application_set_title($str){}

function application_tofront(){}

function application_get_title(){}

function application_prop($prop, $v){}

function dialog_execute($obj){}

function dialog_items($obj){}

function dialog_close($obj){}

function get_key_state($key){}

function reg_hot_key($func, $modifer, $key){}

function keybd_event($func, $modifer, $key){}

function sendkeys($str){}

function tstrings_set_text($obj, $str){}

function tstrings_get_text($obj){}

function tstrings_item_index($obj, $v){}

function tstrings_clear($obj){}

function tstrings_loadfile($obj, $file){}

function tstrings_setline($obj, $LineId, $v){}

function tstream_create(){}

function tstream_read($self, $count){}

function tstream_write($self, $buffer, $count){}

function tstream_seek($self, $offset, $origin){}

function tstream_read_buffer($self, $count){}

function tstream_write_buffer($self, $buffer, $count){}

function tstream_copy_from($self, $obj, $count){}

function tstream_read_component($self, $obj){}

function tstream_read_componentRes($self, $obj){}

function tstream_write_component($self, $obj){}

function tstream_get_position($self){}

function tstream_set_position($self, $v){}

function tstream_get_size($self){}

function tstream_set_size($self, $v){}

function tmstream_create(){}

function tfilestream_create($file, $mode){}

function object_text2resource($param1, $param2){}

function object_resource2text($param1, $param2){}

function tstream_read_component_res($self, $res){}

function tstream_write_component_res($self, $res, $obj){}

function tstream_writestr($self, $str){}

function tstream_readstr($self){}

function tmstream_loadfile($self, $file){}

function tmstream_savefile($self, $file){}

function tmstream_loadstream($self, $TStream){}

function tstream_savestream($self, $stream){}

function picture_loadfile($self, $filename){}

function picture_savefile($self, $filename){}

function tbitmap_create(){}

function bitmap_loadfile($self, $filename){}

function bitmap_savefile($self, $filename){}

function ticon_create(){}

function icon_loadfile($self, $filename){}

function icon_savefile($self, $filename){}

function picture_convert(){}

function bitmap_assign($self, $TBitmap){}

function picture_empty($self){}

function picture_bitmap($self){}

function icon_assign($self, $TIcon){}

function icon_empty($self){}

function picture_assign($self, $TPicture){}

function picture_clear($self){}

function picture_bitmap_assign($self, $TBitmap){}

function icon_assign_ico($self, $TIcon){}

function picture_loadstream($self, $TStream){}

function picture_savestream($self, $TStream){}

function convert_file_to_bmp_border($self, $filename, $border){}

function bitmap_loadstr($self, $str){}

function bitmap_savestr($self){}

function bitmap_canvas($self){}

function bitmap_size($self, $w, $h){}

function picture_loadstr($self, $str, $EXTENSION){}

function ds_imagegrabscreen($x, $y, $w, $h){}

function ds_bmp2jpeg($self, $bmp, $jpeg){}

function registry_create(){}

function registry_command($self, $arg_1, $arg_2, $arg_3, $arg_4, $arg_5){}

function win_set_privilege($name, $v){}

function win_exit_windows($flag, $v){}

function win_sleep(){}

function __winlocalpath($type){}

function mci_command($command, $param){}

function win_addfont($filename){}

function win_delfont($name){}

function win_tempdir(){}

function param_str($index){}

function shell_execute($wait, $command, $file, $program, $mode, $show_mode){}

function lockwindowupdate($handle){}

function __get_handle($obj){}

function control_perform($self, $msg, $hparam, $lparam){}

function shell_execute_wait($file, $params, $mode, $show_mode){}

function kill_task($EXEname){}

function receiver_send($handle, $msg){}

function receiver_handle(){}

function getsystemmetrics($metric){}

function setcursorpos($x, $y){}

function setcursor($cursor){}

function mouse_event($name, $x, $y, $param_1, $param_2){}

function clienttoscreen($handle){}

function clienttoscreenX($handle){}

function clienttoscreenY($handle){}

function screentoclient($handle){}

function trayicon_assign($self, $icon){}

function sendmessage($handle, $msg, $hparam, $lparam){}

function setcurrentdir($dir_name){}

function exists_task($name){}

function shell_execute_wait2($file, $params, $mode, $sw_mode){}

function exemod_start($filename){}

function exemod_addstr($res_name, $str){}

function exemod_extractstr($res_name){}

function exemod_erase($res_name){}

function exemod_saveexe($filename){}

function exemod_addfile($res_name, $filename){}

function exemod_extractfile($res_name, $filename){}

function exemod_extractstream($res_name, $TStream){}

function exemod_addstream($res_name, $TStream){}

function exemod_finish(){}

function random($x){}

/* Skinization ! */

function skins_updateskin($self){}

function skins_thirdparty($self, $type, $value){}

/* End ! */

function control_manualdock($obj_1, $obj_2, $align){}

function control_manualfloat($obj, $left, $top, $right, $bottom){}

function control_dockclientcount($obj){}

function control_dockclient($obj, $index){}

function control_dockorientation($obj){}

function control_docksave($obj, $file){}

function control_dockload($obj, $file){}

function control_floatstyle($obj){}

function control_dock($obj_1, $obj_2, $left, $top, $right, $bottom){}

function control_dockleft($obj){}

function control_docktop($obj){}

function control_dockwidth($obj){}

function control_dockheight($obj){}

function control_dragobject($obj){}

function trayicon_balloontip($trayID, $title, $text, $flag, $timeout){}

function enc_setvalue($enclude_name, $value){}

function enc_getvalue($enclude_name){}

function trayicon_hideballoontip($handle_or_self){}

function chromium_exec($self, $command, $args){}

function chromium_free($self){}

function chromium_prop($self, $command_or_prop, $value){}

// копирует картинку из текста или компонента в буфер обмена
function clipboard_assign($picture, $format = null){}

function gui_propset($object, $property, $value){}
function gui_propget($object, $property){}
function gui_readstr($object, $str){}
function gui_create($class_name_ex){}
function gui_destroy($object){}
function gui_criticalcreate($class_name_ex){}
function gui_criticaldestroy($class_name_ex){}
function gui_confirm($text){}
function gui_doublebuffer($object){}
function gui_formclose($form){}
function gui_formcreate($form){}
function gui_formsetmain($form){}
function gui_formshowmodal($form){}
function gui_gethandle($object){}
function gui_getscrollpos($object){}
function gui_isfocused($object){}
function gui_message($text){}
function gui_owner($object){}
function gui_parent($object){}
function gui_propexists($object, $property){}
function gui_proplist($object){}
function gui_proptype($object, $property){}
function gui_registersuperglobal($name, $v){}
function gui_repaint($object){}
function gui_safedestroy($object){}
function gui_safemessage($text){}
function gui_setfocus($object){}
function gui_setscrollpos($object, $v){}